# Autogenerated
from pydantic import BaseModel, Field
from typing import Optional

class _vars(BaseModel):
    body: str

class CommPostVars(BaseModel):
    itemId: str
    payload: _vars
    parentId: Optional[str] = Field(None)

class CommentPost(BaseModel):
    query: str = Field('\\n  mutation Mutation(\\n    $itemId: StringOrInt!\\n    $payload: CommentEntityInput!\\n    $parentId: StringOrInt\\n  ) {\\n    createPostCommentV2(id: $itemId, payload: $payload, parentId: $parentId) {\\n      id\\n      author {\\n        id\\n        name\\n        displayName\\n        level\\n        avatar {\\n          url\\n        }\\n        creatorTagActive {\\n          tagName\\n          isCreator\\n          isEarlySupporter\\n        }\\n      }\\n      body\\n      isSpam\\n      score\\n      voteCount\\n      createdAt\\n      level\\n      parentId\\n      totalChildComment\\n      canReply\\n      likeStatus\\n      isDeleted\\n      isSuspendedHidden\\n      deletedBy {\\n        id\\n        name\\n        displayName\\n      }\\n      reason\\n      updatedAt\\n    }\\n  }\\n')
    variables: CommPostVars
    operationName: str = Field('Mutation')

# edit
class CommEditVars(BaseModel):
    id: str
    payload: _vars

class CommentEdit(BaseModel):
    query: str = Field('\\n  mutation UpdateSeriesComment(\\n    $id: StringOrInt!\\n    $payload: CommentEntityInput!\\n  ) {\\n    updatePostCommentV2(id: $id, payload: $payload) {\\n      createdAt\\n      author {\\n        id\\n        name\\n        displayName\\n        avatar {\\n          url\\n        }\\n        level\\n        creatorTagActive {\\n          tagName\\n          isCreator\\n          isEarlySupporter\\n        }\\n      }\\n      id\\n      body\\n      isSpam\\n      score\\n      voteCount\\n    }\\n  }\\n')
    variables: CommEditVars
    operationName: str = Field('UpdateSeriesComment')