# Autogenerated
from pydantic import BaseModel, Field
from typing import Optional

class CollectionData(BaseModel): 
      id                : Optional[str]       = Field(None, description="")
      author            : Optional[dict]      = Field(None, description="")
      name              : Optional[int]       = Field(None, description="")
      description       : Optional[str]       = Field(None, description="")
      visibility        : Optional[str]       = Field(None, description="")
      status            : Optional[str]       = Field(None, description="")
      allow_public_edit : Optional[bool]      = Field(None, description="")
      rating            : Optional[str]       = Field(None, description="")
      fav_count         : Optional[int]       = Field(None, description="")
      vote_count        : Optional[int]       = Field(None, description="")
      score             : Optional[int]       = Field(None, description="")
      previews          : Optional[list]      = Field(None, description="")
      is_favorited      : Optional[bool]      = Field(None, description="")
      post_ids          : Optional[list[str]] = Field(None, description="")
      pool_ids          : Optional[list]      = Field(None, description="")
      series_ids        : Optional[list]      = Field(None, description="")
      is_accessible     : Optional[bool]      = Field(None, description="")
      totalComments     : Optional[int]       = Field(None, description="")
      reactions         : Optional[list]      = Field(None, description="")