# Autogenerated
from typing import Any, Literal

from pydantic import BaseModel, Field


# adding/removing item
class collectionAddItem(BaseModel):
      item_id: str
      item_type: str

actions = Literal['add', 'remove']
class collectionRemAddResponse(BaseModel):
      action: actions
      success: bool

# collection data
class collAuthor(BaseModel):
    id: str | None = Field(None)
    name: str | None = Field(None)
    display_name: str | None = Field(None)
    level: int | None = Field(None)
    avatar: str | None = Field(None)
    avatar_rating: str | None = Field(None)

class collPreviewsItemAuthor(BaseModel):
    id: str | None = Field(None)
    name: str | None = Field(None)
    display_name: str | None = Field(None)
    level: int | None = Field(None)
    avatar: str | None = Field(None)
    avatar_rating: str | None = Field(None)

class collPreviewsItemCreated_at(BaseModel):
    json_class: str | None = Field(None)
    s: int | None = Field(None)
    n: int | None = Field(None)

class collPreviewsItemTagsItem(BaseModel):
    id: str | None = Field(None)
    name_en: str | None = Field(None)
    name_ja: str | None = Field(None)
    type: int | None = Field(None)
    count: int | None = Field(None)
    post_count: int | None = Field(None)
    pool_count: int | None = Field(None)
    companion_count: int | None = Field(None)
    series_count: int | None = Field(None)
    locale: str | None = Field(None)
    rating: str | None = Field(None)
    version: int | None = Field(None)
    tagName: str | None = Field(None)
    total_post_count: int | None = Field(None)
    total_pool_count: int | None = Field(None)
    is_following: bool | None = Field(None)
    notification_enabled: bool | None = Field(None)
    name: str | None = Field(None)

class collPreviewsItem(BaseModel)   :
    id: str | None = Field(None)
    rating: str | None = Field(None)
    author: collPreviewsItemAuthor | None = Field(None)
    preview_url: str | None = Field(None)
    preview_width: Any | None = Field(None)
    preview_height: Any | None = Field(None)
    created_at: collPreviewsItemCreated_at | None = Field(None)
    has_comments: bool | None = Field(None)
    has_notes: bool | None = Field(None)
    is_favorited: bool | None = Field(None)
    user_vote: Any | None = Field(None)
    md5: str | None = Field(None)
    comment_count: int | None = Field(None)
    source: str | None = Field(None)
    in_visible_pool: bool | None = Field(None)
    is_premium: bool | None = Field(None)
    is_rating_locked: bool | None = Field(None)
    is_note_locked: bool | None = Field(None)
    is_status_locked: bool | None = Field(None)
    redirect_to_signup: bool | None = Field(None)
    sequence: Any | None = Field(None)
    generation_directives: Any | None = Field(None)
    tags: list[collPreviewsItemTagsItem] | None = Field(None)
    tag_names: list[str] | None = Field(None)
    is_restricted_anonymous_upload: bool | None = Field(None)
    is_anonymous: bool | None = Field(None)
    total_tags: int | None = Field(None)
    reactions: list[Any] | None = Field(None)
    subtitles: list[Any] | None = Field(None)
    audios: list[Any] | None = Field(None)
    gif_preview_url: Any | None = Field(None)

class CollectionData(BaseModel):
    id: str | None = Field(None)
    author: collAuthor | None = Field(None)
    name: str | None = Field(None)
    description: str | None = Field(None)
    visibility: str | None = Field(None)
    status: str | None = Field(None)
    allow_public_edit: bool | None = Field(None)
    rating: str | None = Field(None)
    fav_count: int | None = Field(None)
    vote_count: int | None = Field(None)
    score: int | None = Field(None)
    previews: list[collPreviewsItem] | None = Field(None)
    post_ids: list[str] | None = Field(None)
    pool_ids: list[Any] | None = Field(None)
    series_ids: list[Any] | None = Field(None)
    is_accessible: bool | None = Field(None)
    totalComments: int | None = Field(None)
    reactions: list[Any] | None = Field(None)

# collection creating
VisibilityType = Literal['private', 'public']
class CollectionCreating(collectionAddItem):
    name: str
    description: str | None = Field(None)
    visibility: VisibilityType = Field("private")
    allow_public_edit: bool | None = Field(None)
