  # Autogenerated
from pydantic import BaseModel, Field
from typing import Literal, Optional, List, Any

# adding/removing item
class collectionAddItem(BaseModel):
      item_id: str
      item_type: str

actions = Literal['add', 'remove']
class collectionRemAddResponse(BaseModel):
      action: actions
      success: bool

# collection data
class collAuthor(BaseModel):
      id                   : Optional[str] = Field(None)
      name                 : Optional[str] = Field(None)
      display_name         : Optional[str] = Field(None)
      level                : Optional[int] = Field(None)
      avatar               : Optional[str] = Field(None)
      avatar_rating        : Optional[str] = Field(None)

class collPreviewsItemAuthor(BaseModel):
      id                               : Optional[str] = Field(None)
      name                             : Optional[str] = Field(None)
      display_name                     : Optional[str] = Field(None)
      level                            : Optional[int] = Field(None)
      avatar                           : Optional[str] = Field(None)
      avatar_rating                    : Optional[str] = Field(None)

class collPreviewsItemCreated_at(BaseModel):
      json_class                           : Optional[str] = Field(None)
      s                                    : Optional[int] = Field(None)
      n                                    : Optional[int] = Field(None)

class collPreviewsItemTagsItem(BaseModel):
      id                                 : Optional[str] = Field(None)
      name_en                            : Optional[str] = Field(None)
      name_ja                            : Optional[str] = Field(None)
      type                               : Optional[int] = Field(None)
      count                              : Optional[int] = Field(None)
      post_count                         : Optional[int] = Field(None)
      pool_count                         : Optional[int] = Field(None)
      companion_count                    : Optional[int] = Field(None)
      series_count                       : Optional[int] = Field(None)
      locale                             : Optional[str] = Field(None)
      rating                             : Optional[str] = Field(None)
      version                            : Optional[int] = Field(None)
      tagName                            : Optional[str] = Field(None)
      total_post_count                   : Optional[int] = Field(None)
      total_pool_count                   : Optional[int] = Field(None)
      is_following                       : Optional[bool] = Field(None)
      notification_enabled               : Optional[bool] = Field(None)
      name                               : Optional[str] = Field(None)

class collPreviewsItem(BaseModel)   :
      id                            : Optional[str] = Field(None)
      rating                        : Optional[str] = Field(None)
      author                        : Optional[collPreviewsItemAuthor] = Field(None)
      preview_url                   : Optional[str] = Field(None)
      preview_width                 : Optional[Any] = Field(None)
      preview_height                : Optional[Any] = Field(None)
      created_at                    : Optional[collPreviewsItemCreated_at] = Field(None)
      has_comments                  : Optional[bool] = Field(None)
      has_notes                     : Optional[bool] = Field(None)
      is_favorited                  : Optional[bool] = Field(None)
      user_vote                     : Optional[Any] = Field(None)
      md5                           : Optional[str] = Field(None)
      comment_count                 : Optional[int] = Field(None)
      source                        : Optional[str] = Field(None)
      in_visible_pool               : Optional[bool] = Field(None)
      is_premium                    : Optional[bool] = Field(None)
      is_rating_locked              : Optional[bool] = Field(None)
      is_note_locked                : Optional[bool] = Field(None)
      is_status_locked              : Optional[bool] = Field(None)
      redirect_to_signup            : Optional[bool] = Field(None)
      sequence                      : Optional[Any] = Field(None)
      generation_directives         : Optional[Any] = Field(None)
      tags                          : Optional[List[collPreviewsItemTagsItem]] = Field(None)
      tag_names                     : Optional[List[str]] = Field(None)
      is_restricted_anonymous_upload: Optional[bool] = Field(None)
      is_anonymous                  : Optional[bool] = Field(None)
      total_tags                    : Optional[int] = Field(None)
      reactions                     : Optional[List[Any]] = Field(None)
      subtitles                     : Optional[List[Any]] = Field(None)
      audios                        : Optional[List[Any]] = Field(None)
      gif_preview_url               : Optional[Any] = Field(None)

class CollectionData(BaseModel):
      id                       : Optional[str] = Field(None)
      author                   : Optional[collAuthor] = Field(None)
      name                     : Optional[str] = Field(None)
      description              : Optional[str] = Field(None)
      visibility               : Optional[str] = Field(None)
      status                   : Optional[str] = Field(None)
      allow_public_edit        : Optional[bool] = Field(None)
      rating                   : Optional[str] = Field(None)
      fav_count                : Optional[int] = Field(None)
      vote_count               : Optional[int] = Field(None)
      score                    : Optional[int] = Field(None)
      previews                 : Optional[List[collPreviewsItem]] = Field(None)
      post_ids                 : Optional[List[str]] = Field(None)
      pool_ids                 : Optional[List[Any]] = Field(None)
      series_ids               : Optional[List[Any]] = Field(None)
      is_accessible            : Optional[bool] = Field(None)
      totalComments            : Optional[int] = Field(None)
      reactions                : Optional[List[Any]] = Field(None)

# collection creating
VisibilityType = Literal['private', 'public']
class CollectionCreating(collectionAddItem):
      name                         : str
      description                  : Optional[str] = Field(None)
      visibility                   : VisibilityType = Field('private')
      allow_public_edit            : Optional[bool] = Field(None)
