# Autogenerated
from pydantic import BaseModel, Field
from typing import Optional

class RegisterData(BaseModel):
    success       : Optional[bool]           = Field(None, description="")
    token_type    : Optional[str]            = Field(None, description="")
    access_token  : Optional[str]            = Field(None, description="")
    refresh_token: Optional[str]             = Field(None, description="")
    current_user  : Optional[CurrentUser] = Field(None, description="")

class CurrentUser(BaseModel):
    id                        : Optional[int]  = Field(None, description="")
    name                      : Optional[str]  = Field(None, description="")
    level                     : Optional[int]  = Field(None, description="")
    created_at                : Optional[str]  = Field(None, description="")
    avatar_url                : Optional[str]  = Field(None, description="")
    avatar_rating             : Optional[str]  = Field(None, description="")
    last_logged_in_at         : Optional[str]  = Field(None, description="")
    email_verification_status: Optional[str]   = Field(None, description="")
    is_verified               : Optional[bool] = Field(None, description="")
    email                     : Optional[str]  = Field(None, description="")
    mfa_method                : Optional[int]  = Field(None, description="")