# Autogenerated
from pydantic import BaseModel, Field
from typing import Optional
from models.accountdata import BaseAccountData

class RegisterData(BaseModel):
    success       : Optional[bool]            = Field(None, description="")
    token_type    : Optional[str]             = Field(None, description="")
    access_token  : Optional[str]             = Field(None, description="")
    refresh_token: Optional[str]              = Field(None, description="")
    current_user  : Optional[BaseAccountData] = Field(None, description="")