  # Autogenerated
from pydantic import BaseModel, Field
from typing import Optional
from models.postdata import PostData

class SearchData(BaseModel): 
    meta                 : Optional[_Meta]       = Field(None, description="")
    data                 : Optional[list[PostData]] = Field(None, description="")

class _Meta(BaseModel): 
    next            : Optional[str] = Field(None, description="")
    prev            : Optional[str] = Field(None, description="")
    page_count      : Optional[int] = Field(None, description="")