# Autogenerated
from enum import IntEnum

from pydantic import BaseModel, Field
from typing import Optional

class TaggingData(BaseModel):
    success : Optional[bool]          = Field(None, description="")
    tags    : Optional[list[TagData]] = Field(None, description="")

class TagData(BaseModel):
    id               : Optional[str]     = Field(None, description="")
    name             : Optional[str]     = Field(None, description="")
    name_en          : Optional[str]     = Field(None, description="")
    name_ja          : Optional[str]     = Field(None, description="")
    type             : Optional[TagType] = Field(None, description="")
    count            : Optional[int]     = Field(None, description="")
    post_count       : Optional[int]     = Field(None, description="")
    pool_count       : Optional[int]     = Field(None, description="")
    companion_count  : Optional[int]     = Field(None, description="")
    series_count     : Optional[int]     = Field(None, description="")
    rating           : Optional[str]     = Field(None, description="")
    tag_translations: Optional[list]     = Field(None, description="")
    similarity       : Optional[float]   = Field(None, description="")

class TagType(IntEnum):
    General   = 0
    Author    = 1

    UNKNOWN_1 = 2

    Franchise = 3

    UNKNOWN_2 = 4

    PhotoSet  = 5
    Genre     = 6

    UNKNOWN_3 = 7

    Medium    = 8

    UNKNOWN_4 = 9

    Fashion   = 10
    Anatomy   = 11
    Pose      = 12

    UNKNOWN_5 = 13

    Role      = 14

    UNKNOWN_6 = 15
    UNKNOWN_7 = 16
    UNKNOWN_8 = 17
    Object    = 18

    UNKNOWN_9 = 19

    Setting   = 20

    UNKNOWN_10 = 21

    Automatic = 22

    UNKNOWN_101 = 23
    UNKNOWN_1011 = 24
    UNKNOWN_1021 = 25
    UNKNOWN_103 = 26
    UNKNOWN_104 = 27
    UNKNOWN_150 = 28
    UNKNOWN_160 = 29
    UNKNOWN_120 = 30