# Autogenerated
from pydantic import BaseModel, Field
from typing import Optional

class TaggingData(BaseModel):
    success : Optional[bool]          = Field(None, description="")
    tags    : Optional[list[TagData]] = Field(None, description="")

class TagData(BaseModel):
    id              : Optional[str]   = Field(None, description="")
    name            : Optional[str]   = Field(None, description="")
    name_en         : Optional[str]   = Field(None, description="")
    name_ja         : Optional[str]   = Field(None, description="")
    type            : Optional[int]   = Field(None, description="")
    count           : Optional[int]   = Field(None, description="")
    post_count      : Optional[int]   = Field(None, description="")
    pool_count      : Optional[int]   = Field(None, description="")
    companion_count : Optional[int]   = Field(None, description="")
    series_count    : Optional[int]   = Field(None, description="")
    rating          : Optional[str]   = Field(None, description="")
    tag_translations: Optional[list]  = Field(None, description="")
    similarity      : Optional[float] = Field(None, description="")